// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnLZC7QNQI_ovE9NeRJ-qhEOndOOmv_S8',
    appId: '1:480743723770:web:ad2ba334b31dd931736f43',
    messagingSenderId: '480743723770',
    projectId: 'neural-canvas-ad9db',
    authDomain: 'neural-canvas-ad9db.firebaseapp.com',
    storageBucket: 'neural-canvas-ad9db.firebasestorage.app',
    measurementId: 'G-QPCDQFJTL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA01aKlXsEuFys5Jk20rCA-SCekfOcPvxg',
    appId: '1:480743723770:android:5ef953732384abae736f43',
    messagingSenderId: '480743723770',
    projectId: 'neural-canvas-ad9db',
    storageBucket: 'neural-canvas-ad9db.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPezOwtB__CwMCJNASmVgpGHJpZzcuWts',
    appId: '1:480743723770:ios:6f6944ab614c599c736f43',
    messagingSenderId: '480743723770',
    projectId: 'neural-canvas-ad9db',
    storageBucket: 'neural-canvas-ad9db.firebasestorage.app',
    iosClientId: '480743723770-qivbe57h69p42p8eg67vlg9o4dggas3f.apps.googleusercontent.com',
    iosBundleId: 'com.mithil.neuralcanvas',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPezOwtB__CwMCJNASmVgpGHJpZzcuWts',
    appId: '1:480743723770:ios:6f6944ab614c599c736f43',
    messagingSenderId: '480743723770',
    projectId: 'neural-canvas-ad9db',
    storageBucket: 'neural-canvas-ad9db.firebasestorage.app',
    iosClientId: '480743723770-qivbe57h69p42p8eg67vlg9o4dggas3f.apps.googleusercontent.com',
    iosBundleId: 'com.mithil.neuralcanvas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnLZC7QNQI_ovE9NeRJ-qhEOndOOmv_S8',
    appId: '1:480743723770:web:a21c0b12aed011f9736f43',
    messagingSenderId: '480743723770',
    projectId: 'neural-canvas-ad9db',
    authDomain: 'neural-canvas-ad9db.firebaseapp.com',
    storageBucket: 'neural-canvas-ad9db.firebasestorage.app',
    measurementId: 'G-KG49F27MQW',
  );
}
